USER_NAME := csteamengine
VIA_ENABLE = no
OLED_ENABLE = no
QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += ili9341_spi
BACKLIGHT_ENABLE = no
PWM_ENABLE = yes
SERIAL_DRIVER = usart
# SRC += ./graphics/layout-1-left.qgf.c
SRC += ./norse20.qff.c
TAP_DANCE_ENABLE = yes
