// #ifndef LCD_ACTIVITY_TIMEOUT
#undef LCD_ACTIVITY_TIMEOUT
#define LCD_ACTIVITY_TIMEOUT 300000
#define QUANTUM_PAINTER_DISPLAY_TIMEOUT LCD_ACTIVITY_TIMEOUT
// #endif

// Uncomment this if you want to configure a secrets.h file
#define FEE_PAGE_COUNT 1
#define QUANTUM_PAINTER_PIXDATA_BUFFER_SIZE 512

#define TAPPING_TERM 150
#define WEAR_LEVELING_LOGICAL_SIZE 1024
#define WEAR_LEVELING_BACKING_SIZE (WEAR_LEVELING_LOGICAL_SIZE * 4)   // 4096

#define VIA_EEPROM_CUSTOM_SIZE 768     // plenty for 4 layers
#define DYNAMIC_KEYMAP_LAYER_COUNT 3
