// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /Users/charliesteenhagen/Desktop/applePhoto-small.png --output /Users/charliesteenhagen/Desktop --format pal16 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_face_length;
extern const uint8_t  gfx_face[19339];
