// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /Users/charliesteenhagen/Desktop/layouts/layer1/left-1-layout.png --output /Users/charliesteenhagen/Desktop/layouts/output --format pal4 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_left_1_layout_length;
extern const uint8_t  gfx_left_1_layout[6060];
