// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /Users/charliesteenhagen/Desktop/mist-layers/layer-1-full.png --output /Users/charliesteenhagen/Desktop/mist-layers/output --format pal4 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_layer_1_full_length;
extern const uint8_t  gfx_layer_1_full[6135];
