// Copyright 2025 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image --input /Users/charliesteenhagen/qmk_userspace/norse20.png --output /Users/charliesteenhagen/qmk_userspace --no-ascii False --unicode-glyphs  --format mono4 --no-rle False`

#pragma once

#include <qp.h>

extern const uint32_t font_norse20_length;
extern const uint8_t  font_norse20[3318];
